# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=75)),
                ('alamat', models.CharField(max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anggota',
                'verbose_name_plural': 'Data Anggota',
            },
        ),
        migrations.CreateModel(
            name='Pengarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'Pengarang',
                'verbose_name_plural': 'Data Pengarang',
            },
        ),
        migrations.CreateModel(
            name='Pinjam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField(blank=True)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.Anggota', verbose_name=b'Peminjam')),
            ],
            options={
                'verbose_name': 'Pinjam',
                'verbose_name_plural': 'Data Pinjam',
            },
        ),
        migrations.CreateModel(
            name='Pustaka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=75)),
                ('jenis', models.CharField(max_length=75)),
                ('penerbit', models.CharField(max_length=75)),
                ('tahun', models.CharField(max_length=4)),
                ('data_pengarang', models.ManyToManyField(to='peminjaman.Pengarang')),
            ],
            options={
                'verbose_name': 'Pustaka',
                'verbose_name_plural': 'Data Pustaka',
            },
        ),
        migrations.CreateModel(
            name='Telepon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.CharField(max_length=15)),
                ('anggota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.Anggota')),
            ],
            options={
                'verbose_name': 'Telepon',
                'verbose_name_plural': 'Data Telepon',
            },
        ),
        migrations.AddField(
            model_name='pinjam',
            name='data_pustaka',
            field=models.ManyToManyField(to='peminjaman.Pustaka'),
        ),
    ]
