# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjam',
            name='status',
            field=models.IntegerField(choices=[(0, b'Belum Kembali'), (1, b'Sudah Kembali')], default=0),
        ),
        migrations.AlterField(
            model_name='pinjam',
            name='tanggal_kembali',
            field=models.DateField(),
        ),
    ]
